### ISSUE TITLE
No Electron Please!!!

### ISSUE THREAD

**Issue by codingbox** [7086cmd/stunning-new#7]
I'm byh, a student from Jiaochuan Academy.
Actually some classrooms only have Core i3 Gen 4 (2C/4T), 4 GB Ram, and HDD.
WebUI is as powerful as electron apps.

**Comment by codingbox** [comment]
Or just write a web api, and use qt to do it.

**Comment by 7086cmd** [comment]
What is the class number?
Vue 3.0 ** ONLY ** support for high version.
Now **Here is a problem that** we have to support this options:
- Notifications
- A browser which is support for `Vue.js 3.0`
- A browser which is support for `Vite 2.0`(**ESM Support**) unless I open the `Lagacy` option.

**Comment by codingbox** [comment]
Edge and Chrome don't support? Windows 7 can update to the latest chrome/edge version, too.

**Comment by 7086cmd** [comment]
> Edge and Chrome don't support? Windows 7 can update to the latest chrome/edge version, too.

Microsoft and Google give them a highest version in stop-supportion time.

**Comment by codingbox** [comment]
But electron-app is too **fat** to install.

![image.png](https://s2.loli.net/2021/12/08/BbTF678u1khOWHz.png)

**Comment by codingbox** [comment]
And you can't update apps easily.
Auto-update is difficult, because nginx/apache/caddy is difficult to use.

**Comment by 7086cmd** [comment]
I had a meeting with other core members.
I ask them *If I run it on applications but it takes a lot of memory, what will them think of*, and they says OK.

About Auto-Update, `Electon app will not show "safe" or not, and no baby can attack this machine because of belief(/xyx)`

**Comment by 7086cmd** [comment]
So... I can not to use `https` if I have no `Https License`. So I can not use the linux framework you say.

**Comment by 7086cmd** [comment]
About app pages,
I can hang the we pages in this app.

**Comment by 7086cmd** [comment]
Because this is only a back-end and front-end app run at the server, I can run it with electron.

**Comment by codingbox** [comment]
You must know WebUI is similar to app.
And many classes' computer admin use 360-family apps.
WebUI can give message too.
Such as <https://loc.nage.ltd/>

**Comment by 7086cmd** [comment]
实在不行，我可以使用`PWA`，就像我现在实在不行使用了中文一样。

**Comment by codingbox** [comment]
> 实在不行，我可以使用`PWA`，就像我现在实在不行使用了中文一样。

right.
